# **Laboratory Task 5**

---

1. Perform Standard Imports

In [1]:
import numpy as np
import torch

2. Create a function called `set_seed()` that accepts `seed: int` as a parameter, this function must return nothing but just set the seed to a certain value.

In [2]:
def set_seed(seed: int):
    np.random.seed(seed)

3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the `set_seed()` function and use 42 as the seed parameter.

In [3]:
seed = 42
set_seed(seed)
arr = np.random.randint(low=0, high=5, size=6)
arr

array([3, 4, 2, 4, 4, 1], dtype=int32)

4. Create a tensor "x" from the array above.

In [4]:
x = torch.from_numpy(arr)
x

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)

5. Change the dtype of `x` from `int32` to `int64`.

In [5]:
x = x.type(torch.int64)
x

tensor([3, 4, 2, 4, 4, 1])

6. Reshape `x` into a 3x2 tensor.

In [6]:
x = x.reshape(3,2)
x

tensor([[3, 4],
        [2, 4],
        [4, 1]])

7. Return the right-hand column of tensor `x`.

In [7]:
x[:,1]

tensor([4, 4, 1])

8. Without changing `x`, return a tensor of square values of `x`.

In [8]:
torch.square(x)

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])

9. Create a tensor `y` with the same number of elements as `x`, that can be matrix-multiplied with `x`.

In [9]:
torch.manual_seed(seed)
y = torch.randint_like(x.T, 0, 5)
y

tensor([[2, 1, 1],
        [2, 4, 0]])

10. Find the matrix product of `x` and `y`.

In [10]:
torch.mm(x,y)

tensor([[14, 19,  3],
        [12, 18,  2],
        [10,  8,  4]])